ARG EVALSCOPE_BASE_IMAGE=python:3.11-slim

FROM ${EVALSCOPE_BASE_IMAGE}

WORKDIR /app

ENV PIP_NO_CACHE_DIR=1
ENV PIP_INDEX_URL=https://mirrors.aliyun.com/pypi/simple/
ENV PIP_TIMEOUT=120
ENV PIP_RETRIES=5

RUN pip install --upgrade pip setuptools wheel \
  && pip install --no-build-isolation "evalscope[service]" uvicorn

RUN mkdir -p /app/outputs

EXPOSE 9000

CMD ["evalscope", "service", "--host", "0.0.0.0", "--port", "9000", "--outputs", "/app/outputs"]
